title: <p align="center"> Morgan Ford </p> # your name (or website title) here
logo: "/images/gradphotos2022-17-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/Morgan Ford_resume_update_5.24.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/morgan-ford-7b994b160/">LinkedIn</a> |
  <a href="https://github.com/fordm02">GitHub</a>
  </p>
  
  <p align="justify">
  I am a recent graudate with a MS degree in Applied Mathematics at Rensselaer Polytechnic Institute.
  <br><br>
  I am currently a Graduate Student Researcher with the Rensselaer Institute for Data Exploration and Applications (IDEA).
  <br><br>
  Relevant Coursework: Intro to Machine Learning Applications, Data Analytics Research, Data Analytics, Big Data Policy, Intro to Data Math, Statistical Analysis
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-316782735 # your Google Analytics tracking ID here
